// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Testers.Infrastructure.Persistence;

#nullable disable

namespace Testers.Infrastructure.Persistence.Migrations.TestPlan
{
    [DbContext(typeof(TestPlanDbContext))]
    partial class TestPlanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Testers.Domain.Execution.TaskRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("ActionedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("actioned_at");

                    b.Property<Guid>("BuildId")
                        .HasColumnType("TEXT")
                        .HasColumnName("build_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_by");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER")
                        .HasColumnName("outcome");

                    b.Property<Guid>("TaskDefinitionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("task_definition_id");

                    b.Property<string>("TesterId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("tester_id");

                    b.HasKey("Id")
                        .HasName("pk_task_run");

                    b.HasIndex("BuildId", "TaskDefinitionId")
                        .HasDatabaseName("ix_task_run_build_id_task_definition_id");

                    b.HasIndex("TesterId", "ActionedAt")
                        .HasDatabaseName("ix_task_run_tester_id_actioned_at");

                    b.ToTable("task_run", (string)null);
                });

            modelBuilder.Entity("Testers.Domain.Execution.TaskRun", b =>
                {
                    b.OwnsMany("Testers.Domain.Execution.BugLink", "BugLinks", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT")
                                .HasColumnName("id");

                            b1.Property<string>("BugTrackerUrl")
                                .HasMaxLength(1000)
                                .HasColumnType("TEXT")
                                .HasColumnName("bug_tracker_url");

                            b1.Property<string>("ExternalBugId")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("external_bug_id");

                            b1.Property<DateTime>("LinkedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("linked_at");

                            b1.Property<Guid>("TaskRunId")
                                .HasColumnType("TEXT")
                                .HasColumnName("task_run_id");

                            b1.HasKey("Id")
                                .HasName("pk_task_run_bug_link");

                            b1.HasIndex("TaskRunId")
                                .HasDatabaseName("ix_task_run_bug_link_task_run_id");

                            b1.ToTable("task_run_bug_link", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TaskRunId")
                                .HasConstraintName("fk_task_run_bug_link_task_run_task_run_id");
                        });

                    b.OwnsMany("Testers.Domain.Execution.Comment", "Comments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT")
                                .HasColumnName("id");

                            b1.Property<DateTime>("AddedAt")
                                .HasColumnType("TEXT")
                                .HasColumnName("added_at");

                            b1.Property<string>("AuthorId")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("author_id");

                            b1.Property<string>("Body")
                                .IsRequired()
                                .HasMaxLength(10000)
                                .HasColumnType("TEXT")
                                .HasColumnName("body");

                            b1.Property<Guid>("TaskRunId")
                                .HasColumnType("TEXT")
                                .HasColumnName("task_run_id");

                            b1.HasKey("Id")
                                .HasName("pk_task_run_comment");

                            b1.HasIndex("TaskRunId")
                                .HasDatabaseName("ix_task_run_comment_task_run_id");

                            b1.ToTable("task_run_comment", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TaskRunId")
                                .HasConstraintName("fk_task_run_comment_task_run_task_run_id");
                        });

                    b.Navigation("BugLinks");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
