<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Scrutor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Testers.Domain\Testers.Domain.csproj" />
    <ProjectReference Include="..\Testers.Contracts\Testers.Contracts.csproj" />
    <ProjectReference Include="..\Testers.SharedKernel\Testers.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Testers.UnitTests" />
    <InternalsVisibleTo Include="Testers.IntegrationTests" />
  </ItemGroup>

</Project>
