<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Testers.Infrastructure\Testers.Infrastructure.csproj" />
    <ProjectReference Include="..\Testers.Contracts\Testers.Contracts.csproj" />
  </ItemGroup>

</Project>
