// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Testers.Infrastructure.Persistence;

#nullable disable

namespace Testers.Infrastructure.Persistence.Migrations.App
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Testers.Infrastructure.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EntityKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_key");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_type");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at");

                    b.Property<string>("StateJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("state_json");

                    b.Property<string>("UserDisplayName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_log_occurred_at");

                    b.HasIndex("EntityType", "EntityKey")
                        .HasDatabaseName("ix_audit_log_entity_type_entity_key");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Testers.Infrastructure.Auth.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("key_hash");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_used_at");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_id");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("prefix");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("scopes");

                    b.HasKey("Id")
                        .HasName("pk_api_key");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_api_key_key_hash");

                    b.ToTable("api_key", (string)null);
                });

            modelBuilder.Entity("Testers.Infrastructure.Outbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("message_id");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("consumer_name");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("processed_at");

                    b.HasKey("MessageId", "ConsumerName")
                        .HasName("pk_inbox_message");

                    b.ToTable("inbox_message", (string)null);
                });

            modelBuilder.Entity("Testers.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("processed_at");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("routing_key");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("ProcessedAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_message_processed_at_occurred_at");

                    b.ToTable("outbox_message", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
